### ISSUE TITLE
Better handling of "non-monotonically increasing dts to muxer" errors

### ISSUE THREAD

**Issue by jailuthra** [livepeer/lpms#227]
A very frequent error while transcoding occurs with the following logs:
```
[mpegts @ 0x7f277c4fb880] Application provided invalid, non monotonically increasing dts to muxer in stream 1: 181812 >= 181812
ERROR: transcoder.c:267] Error encoding : Invalid argument
```

**TODO:**
- [ ] Find root-cause
- [ ] Improve logs around it
- [ ] Fix it/handle it better
