### ISSUE TITLE
Tracking FFmpeg Native Integration

### ISSUE THREAD

**Issue by j0sh** [livepeer/lpms#47]
We will be implementing exactly what we need via C and exposing that via CGo. Proof of concept: https://gist.github.com/j0sh/05252a48edd163b01e65f1b363de1631#file-rtmp2hls-go

See https://github.com/livepeer/lpms/issues/24 for some groundwork towards this, and why we aren't using an existing FFmpeg-Go binding.

- [x] RTMP to HLS Segmentation
- [x] Transcoding
- [x] ~~Camera capture on OSX~~ (Feature removed in https://github.com/livepeer/go-livepeer/commit/395fe8a25e1641be848f19f21730383c74922806)
- [x] ~~Possibly replace joy4 RTMP ingest with FFmpeg -- https://github.com/livepeer/lpms/issues/32 (needs discussion)~~ (Shelved)

**Comment by j0sh** [comment]
On replacing Joy4 with FFMpeg. Relates to https://github.com/livepeer/lpms/issues/32

Pros:
+ One less dependency in Go.
+ FFmpeg offers better compatibility and regular maintenance
+ Possibly a simpler API for LPMS

Cons:
- Having multiple incoming RTMP streams would be more work. We might have to proxy TCP internally to separate instances of a FFmpeg RTMP listener.
- Publishing RTMP to subscribers (RTMP-to-RTMP) would be additional work on top of that. Is RTMP-to-RTMP a desirable use case, or something we happen to get for free with joy4?

**Comment by ericxtang** [comment]
Re-joy4: I think the fact we lose multiple incoming RTMP is a big enough reason to postpone replacing it with FFmpeg - especially considering that we haven't felt any real pain with using it.

RTMP-to-RTMP is not a real usecase at the moment, but I can see it being useful if we want to delay the end-to-end latency of the broadcast. (Especially in a mobile use case)

Question - IF we wanted to use RTMP in the verification process instead of HLS segments, is there an easy way to ensure the input to the verifier is exactly the same as the input to the transcoder?  (I would imagine this has to be enforced on a keyframe level somehow?)

**Comment by j0sh** [comment]
> IF we wanted to use RTMP in the verification process instead of HLS segments, is there an easy way to ensure the input to the verifier is exactly the same as the input to the transcoder?

That's a whole different ballgame for sure, especially if the verifier is not going to be grabbing the live stream. I've thought about this a little bit in the past, but still not sure how to be completely trustless: ensuring that the live stream the broadcaster is sending the transcoder *right now*  is exactly the same as the non-live stream that the verifier will be checking *later*. There's a lot of things that could happen in between. Having the verifier and transcoder pull from the same public, signed source sidesteps a lot of these issues. In any case, this is a good topic to keep thinking about and discuss.

**Comment by j0sh** [comment]
> IF we wanted to use RTMP in the verification process instead of HLS segments, is there an easy way to ensure the input to the verifier is exactly the same as the input to the transcoder?

That's a whole different ballgame for sure.  Presumably both the transcoder and verifier would be pulling RTMP? Calculating the bit-exactness of the transmitted data is easy enough, the difficulty is to be completely trustless (3 ways -- between the broadcaster, verifier and transcoder) without pulling from the blockchain. We might be able to borrow ideas from Raiden or Plasma for ways to conduct such checking in an off-chain manner. Any other ideas? Definitely an open question, and good to keep thinking and discussing.

**Comment by j0sh** [comment]
If the purpose of RTMP is to to reduce latency, then transcoders and verifiers would have to operate without the guarantee of a signature, otherwise we introduce latency equivalent to that of a segment. So the worst case is they lose two or three 'segments' worth of work to a problematic broadcaster. Doing the signing on a frame-by-frame basis seems heavy, but I wonder if there's a way to take advantage of eg, TLS  (RTMPS) with specially signed certs . Not sure how fraud proofs would work with TLS though.

**Comment by dob** [comment]
Yah, I think we'll track research on these fronts here: https://github.com/livepeer/research/issues/2

On another note, I'm also interested in prototyping a fully social verification of work. Build a tool that pulls the original + transcoded challenged segments from IPFS and displays them alongside the transcoder in the Transcoder Election DApp. Users would be pretty capable of eyeballing rough correctness here (or at least spot blatant cheating). This would not be cryptographically secure by any means, but I'm interested in testing whether the penalty of losing one's job due to hurting the network stands up.
